import {describe,expect,it} from "vitest";
import {unzipSync,strFromU8} from "fflate";
import {createAssetImportTemplateXlsx,createAssetXlsx} from "./xlsx-export";
import {parseAssetWorkbook} from "./xlsx-assets";
describe("createAssetXlsx",()=>{
  it("creates a workbook that can be imported back without losing fields or embedded photos",()=>{const buffer=createAssetXlsx([{no:1,assetNumber:"A-001",assetCode:"P-01",assetClass:"Pump",description:"Pompa & Motor",bookValue:1200,acquisitionValue:1500,quantity:1,maintenance:"Decommissioned",documentationNote:"Manual",layout:"Area A",coordinateText:"-0.9, 104.5",exportPhotos:[{bytes:new Uint8Array([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]),contentType:"image/png"}]}]);const archive=unzipSync(buffer);expect(archive["xl/workbook.xml"]).toBeDefined();const sheet=strFromU8(archive["xl/worksheets/sheet1.xml"]);expect(sheet).toContain("Pompa &amp; Motor");expect(sheet).not.toContain("Kebutuhan Data");expect(sheet).not.toContain("Biaya Pemeliharaan/Maintenance");expect(sheet).toContain('<c r="A2" s="0"><v>1</v></c>');const parsed=parseAssetWorkbook(buffer);expect(parsed.errors).toEqual([]);expect(parsed.imageCount).toBe(1);expect(parsed.rows[0]).toMatchObject({assetNumber:"A-001",maintenanceStatus:"Decommissioned",documentation:"Manual",coordinateText:"-0.9, 104.5",latitude:-0.9,longitude:104.5});});

  it("creates an empty import template with complete headers, status validation, and photo instructions",()=>{const buffer=createAssetImportTemplateXlsx();const archive=unzipSync(buffer);const workbook=strFromU8(archive["xl/workbook.xml"]);const assetSheet=strFromU8(archive["xl/worksheets/sheet1.xml"]);const instructions=strFromU8(archive["xl/worksheets/sheet2.xml"]);expect(workbook).toContain('name="Daftar Aset"');expect(workbook).toContain('name="Petunjuk Import"');expect(assetSheet).toContain('r="Q1"');expect(assetSheet).toContain('sqref="O2:O5000"');expect(assetSheet).toContain("Decommissioned");expect(instructions).toContain("Insert → Pictures");expect(instructions).toContain("kolom Dokumentasi (M)");expect(parseAssetWorkbook(buffer)).toMatchObject({rows:[],errors:[],imageCount:0});});
});
