import { strToU8,zipSync } from "fflate";
import { ASSET_STATUSES } from "./asset-status";

export interface ExportAssetPhoto { bytes: Uint8Array; contentType: "image/jpeg"|"image/png"|"image/webp" }
export type ExportAssetRow = Record<string,unknown> & { exportPhotos?: ExportAssetPhoto[] };

const headers=["No","No Asset","Capitalized on","Kode Aset","Class Asset","Asset description","Acquis.val.","Book val.","Quantity","Base Unit of Measure","Location","Sub Asset","Dokumentasi","Lokasi / Layout","Status Aset","Frekuensi Pemakaian","Koordinat"];
const keys=["no","assetNumber","capitalizedOn","assetCode","assetClass","description","acquisitionValue","bookValue","quantity","unit","location","subAsset","documentationNote","layout","maintenance","usageFrequency","coordinateText"];
function escape(value:unknown){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");}
function letter(index:number){let output="";for(let value=index+1;value>0;value=Math.floor((value-1)/26))output=String.fromCharCode(65+(value-1)%26)+output;return output;}
function cell(reference:string,value:unknown,style=0){if(typeof value==="number"&&Number.isFinite(value))return `<c r="${reference}" s="${style}"><v>${value}</v></c>`;return `<c r="${reference}" s="${style}" t="inlineStr"><is><t>${escape(value)}</t></is></c>`;}
function photoExtension(contentType:ExportAssetPhoto["contentType"]){return contentType==="image/jpeg"?"jpg":contentType.split("/")[1];}
export function createAssetXlsx(rows:Array<ExportAssetRow>, options: { importTemplate?: boolean } = {}){
  const importTemplate=options.importTemplate===true;
  const table=[headers,...rows.map(row=>keys.map(key=>key==="capitalizedOn"&&row[key]?new Date(String(row[key])).toISOString().slice(0,10):key==="no"||key==="acquisitionValue"||key==="bookValue"||key==="quantity"?Number(row[key]??0):row[key]??""))];
  const sheetRows=table.map((row,rowIndex)=>`<row r="${rowIndex+1}"${rowIndex>0&&rows[rowIndex-1]?.exportPhotos?.length?' ht="90" customHeight="1"':""}>${row.map((value,columnIndex)=>cell(`${letter(columnIndex)}${rowIndex+1}`,value,rowIndex===0?1:columnIndex===6||columnIndex===7?2:0)).join("")}</row>`).join("");
  const photos=rows.flatMap((row,rowIndex)=>(row.exportPhotos??[]).map((photo,photoIndex)=>({photo,rowIndex,photoIndex})));
  const drawing=photos.length?`<?xml version="1.0" encoding="UTF-8"?><xdr:wsDr xmlns:xdr="http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">${photos.map((item,index)=>`<xdr:oneCellAnchor><xdr:from><xdr:col>12</xdr:col><xdr:colOff>${item.photoIndex*1450000}</xdr:colOff><xdr:row>${item.rowIndex+1}</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:from><xdr:ext cx="1400000" cy="1100000"/><xdr:pic><xdr:nvPicPr><xdr:cNvPr id="${index+1}" name="Foto Aset ${index+1}"/><xdr:cNvPicPr><a:picLocks noChangeAspect="1"/></xdr:cNvPicPr></xdr:nvPicPr><xdr:blipFill><a:blip r:embed="rId${index+1}"/><a:stretch><a:fillRect/></a:stretch></xdr:blipFill><xdr:spPr><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></xdr:spPr></xdr:pic><xdr:clientData/></xdr:oneCellAnchor>`).join("")}</xdr:wsDr>`:"";
  const drawingRels=photos.length?`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${photos.map((item,index)=>`<Relationship Id="rId${index+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="../media/image${index+1}.${photoExtension(item.photo.contentType)}"/>`).join("")}</Relationships>`:"";
  const files:Record<string,Uint8Array>={
    "[Content_Types].xml":strToU8(`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="jpg" ContentType="image/jpeg"/><Default Extension="png" ContentType="image/png"/><Default Extension="webp" ContentType="image/webp"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>${importTemplate?'<Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>':""}<Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${photos.length?'<Override PartName="/xl/drawings/drawing1.xml" ContentType="application/vnd.openxmlformats-officedocument.drawing+xml"/>':""}</Types>`),
    "_rels/.rels":strToU8(`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`),
    "xl/workbook.xml":strToU8(`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Daftar Aset" sheetId="1" r:id="rId1"/>${importTemplate?'<sheet name="Petunjuk Import" sheetId="2" r:id="rId3"/>':""}</sheets></workbook>`),
    "xl/_rels/workbook.xml.rels":strToU8(`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>${importTemplate?'<Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/>':""}</Relationships>`),
    "xl/styles.xml":strToU8(`<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><numFmts count="1"><numFmt numFmtId="164" formatCode="&quot;Rp&quot; #,##0.00"/></numFmts><fonts count="2"><font/><font><b/><color rgb="FFFFFFFF"/></font></fonts><fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF12382F"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="3"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="1" borderId="0" xfId="0" applyFont="1" applyFill="1"/><xf numFmtId="164" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/></cellXfs></styleSheet>`),
    "xl/worksheets/sheet1.xml":strToU8(`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>${[7,18,15,15,20,38,16,16,12,20,24,20,34,24,22,24,28].map((width,index)=>`<col min="${index+1}" max="${index+1}" width="${width}" customWidth="1"/>`).join("")}</cols><sheetData>${sheetRows}</sheetData><autoFilter ref="A1:Q${Math.max(table.length,2)}"/>${importTemplate?`<dataValidations count="1"><dataValidation type="list" allowBlank="1" showInputMessage="1" promptTitle="Status Aset" prompt="Pilih status dari daftar" sqref="O2:O5000"><formula1>&quot;${ASSET_STATUSES.join(",")}&quot;</formula1></dataValidation></dataValidations>`:""}${photos.length?'<drawing r:id="rId1"/>':""}</worksheet>`),
  };
  if(importTemplate){
    const instructions=[
      ["FORMAT IMPORT XASSET","Isi data pada sheet 'Daftar Aset'. Satu baris untuk satu aset."],
      ["Kolom wajib","No Asset, Kode Aset, Asset description, Acquis.val., Book val., Quantity."],
      ["Foto otomatis","Pada sheet Daftar Aset pilih Insert → Pictures. Pindahkan gambar agar sudut kiri atas gambar berada di kolom Dokumentasi (M) dan pada baris aset yang sama. Beberapa foto boleh ditempatkan pada baris yang sama."],
      ["Format foto","JPG, PNG, atau WebP; maksimal 10 MB per foto. Ukuran seluruh workbook maksimal 50 MB."],
      ["Koordinat","Gunakan format latitude, longitude. Contoh: 0.9227000, 104.5323000."],
      ["Capitalized on","Gunakan tanggal Excel atau format YYYY-MM-DD."],
      ["Status Aset",ASSET_STATUSES.join(" | ")],
      ["Catatan penting","Jangan mengubah nama header. Hapus semua baris contoh milik Anda yang tidak ingin diimpor. Foto harus berupa gambar tertanam, bukan URL atau nama file."],
      ["Proses import","Pilih Import XLSX → validasi/preview → konfirmasi. Aplikasi membuat data aset dan mengunggah seluruh foto tertanam secara otomatis."],
    ];
    const instructionRows=instructions.map((row,index)=>`<row r="${index+1}" ht="${index===0?28:42}" customHeight="1">${cell(`A${index+1}`,row[0],index===0?1:0)}${cell(`B${index+1}`,row[1],0)}</row>`).join("");
    files["xl/worksheets/sheet2.xml"]=strToU8(`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><cols><col min="1" max="1" width="24" customWidth="1"/><col min="2" max="2" width="115" customWidth="1"/></cols><sheetData>${instructionRows}</sheetData></worksheet>`);
  }
  if(photos.length){files["xl/worksheets/_rels/sheet1.xml.rels"]=strToU8(`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/drawing" Target="../drawings/drawing1.xml"/></Relationships>`);files["xl/drawings/drawing1.xml"]=strToU8(drawing);files["xl/drawings/_rels/drawing1.xml.rels"]=strToU8(drawingRels);photos.forEach((item,index)=>{files[`xl/media/image${index+1}.${photoExtension(item.photo.contentType)}`]=item.photo.bytes;});}
  return zipSync(files,{level:6});
}

export function createAssetImportTemplateXlsx(){return createAssetXlsx([],{importTemplate:true});}
