import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { requireApiPermission } from "@/server/api-auth";
import { writeAudit } from "@/server/audit";
import { query } from "@/server/db";

const resources={classes:"asset_classes",categories:"asset_categories",units:"units_of_measure",frequencies:"usage_frequencies",sites:"sites",locations:"locations"} as const;
const input=z.object({code:z.string().trim().min(1).max(80),name:z.string().trim().min(1).max(255)}).partial().refine(value=>Object.keys(value).length>0);
interface Context{params:Promise<{resource:string;id:string}>}
export async function PATCH(request:NextRequest,context:Context){const auth=await requireApiPermission(request,"admin:manage");if(auth instanceof NextResponse)return auth;const {resource,id}=await context.params;const table=resources[resource as keyof typeof resources];if(!table)return NextResponse.json({error:"NOT_FOUND"},{status:404});const parsed=input.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"INVALID_MASTER_DATA"},{status:422});const fields=Object.entries(parsed.data);const result=await query(`UPDATE ${table} SET ${fields.map(([key],index)=>`${key}=$${index+1}`).join(",")} WHERE id=$${fields.length+1} RETURNING id,code,name`,[...fields.map(([,value])=>value),id]);if(!result.rows[0])return NextResponse.json({error:"NOT_FOUND"},{status:404});await writeAudit({actor:auth,action:"master.update",resourceType:resource,resourceId:id,after:result.rows[0]});return NextResponse.json({data:result.rows[0]});}
export async function DELETE(request:NextRequest,context:Context){const auth=await requireApiPermission(request,"admin:manage");if(auth instanceof NextResponse)return auth;const {resource,id}=await context.params;const table=resources[resource as keyof typeof resources];if(!table)return NextResponse.json({error:"NOT_FOUND"},{status:404});try{const result=await query(`DELETE FROM ${table} WHERE id=$1 RETURNING id,code,name`,[id]);if(!result.rows[0])return NextResponse.json({error:"NOT_FOUND"},{status:404});await writeAudit({actor:auth,action:"master.delete",resourceType:resource,resourceId:id,before:result.rows[0]});return NextResponse.json({ok:true});}catch(error){if((error as {code?:string}).code==="23503")return NextResponse.json({error:"MASTER_DATA_IN_USE"},{status:409});throw error;}}
